name = "Deep Cave phase"
weight = 1

blocks = [
    "20xminecraft:deepslate",
    "14xminecraft:tuff",
    "5xminecraft:amethyst_block",
    "4xminecraft:deepslate_coal_ore",
    "4xminecraft:deepslate_iron_ore",
    "2xminecraft:deepslate_gold_ore",
    "4xminecraft:deepslate_copper_ore",
    "1xminecraft:deepslate_diamond_ore",
    "2xminecraft:deepslate_redstone_ore",
    "3xminecraft:deepslate_lapis_ore",
    "2xminecraft:redstone_ore",
    "2xminecraft:lapis_ore",
    "1xminecraft:emerald_ore"
]

trades = [
    "1xminecraft:lava_bucket; 16-32xminecraft:iron_ingot; 1xminecraft:bucket; 3 25%",
    "trade:farm-3",
    "trade:mobs-3"
]

[unlock]
blocks = 300
command = false
game-time = -1
unlock-time = 9600

[on-research]
trades = [
    "1xminecraft:bamboo; 36-64xminecraft:oak_sapling; 1-3",
    "1xminecraft:lava_bucket; 16-32xminecraft:cobblestone; 1xminecraft:bucket; 3",
    "4xminecraft:glow_berries; 16-24xminecraft:moss_block; 8-12",
    "4xminecraft:sweet_berries; 8-12xminecraft:moss_block; 8-12",
    "1xminecraft:pointed_dripstone; 8-24xminecraft:cobblestone; 6-12"
]
trader-message = "{b,c=#ffffff}Wandering trader{r}: {c=#75FA8D}Finally some light!"
