name = "Growing phase"  # Helps you to check your tier with info command.
# The wight of tier when choosing between enabled tiers.
weight = 3
# Blocks you want to gurantee to be spawned when this tier is unlocked!
# The format is the same as blocks, also used in sequences.toml.
# If empty or missing, a random block will be chosen like normal.
starting-blocks = [
    "neoblock:chest:tier1-chest",
    "3xminecraft:stone"
]
# List of all blocks in this tier. All of them have equal chance to be chosen in this tier.
# Note that, blocks from tier 0 are available
blocks = [
    "10xminecraft:stone",
    "4xminecraft:coal_ore",
    "2xminecraft:iron_ore",
    "minecraft:andesite",
    "minecraft:granite",
    "minecraft:diorite",
    "minecraft:clay",
    "neoblock:chest:casual-chest",      # The chests are in chests.toml
    "neoblock:sequence:stone-pot",      # The sequences are in sequences.toml
    "neoblock:sequence:three-stones"
]
# The trades the trader will spawn with when this tier is enabled. This trader will despawn (if not dead) upon unlocking next tier.
# Syntax for item is `COUNT`x`ID`, the count can be a range like `8-12` or a number.
# Uses also use same syntax as the count, but not providing it will use 1 instead.
# For a trade use one of the following:
#    `RESULT`; `COST A`; `COST B`; `USES`
#    `RESULT`; `COST A`; `COST B`;
#    `RESULT`; `COST A`; `USES`
#    `RESULT`; `COST A`;
# ----------------------------------------------------------------------------------------------------------------------
# Wandering NeoTraders will spawn when they have some offers
# List of offers they might have when spawned. using same syntax.
trades = [
    "trade:farm-1",
    "trade:mobs-1",
    "1xminecraft:ice; 2-4xminecraft:oak_log; 8-16xminecraft:dirt; 8-12 60%"
]

# Conditions to unlock the mod, all conditions must be met to unlock.
[unlock]
blocks = 50         # Amount of blocks needed to be broken, set to -1 to deactivate
command = false     # If server has to execute a command to unlock this. /neoblock tiers satisfy <tier-number>
game-time = -1      # Amount of ticks world has been loaded, set to -1 to deactivate
unlock-time = 1200  # Upgrade time in ticks. During upgrade the NeoBlock will turn into Bedrock.

# The event system (Could be called reward system) has 4 static and 3 dynamic types. Static ones are:
# on-unlock: Which is when the research/unlocking is done.
# on-enable: When the tier is enabled. When unlocked it will be enabled immediatly.
# on-disable: When tier is disabled.
# on-research: When the research starts.
# Dyniamic ones are:
# on-X(st|nd|rd|th)-block: Like `on-10th-block`, triggers when the Xth block from this tier is broken.
# on-every-X-block: Like `on-every-10-block`, triggers when every X block from this tier is broken.
#                   For example on 10th, 20th, 30th and so on
# on-every-X-block-offset-Y: Like `on-every-10-block-offset-5`, triggers when every X block from this tier with an offset of Y is broken.
#                            For example on 15th, 25th, 35th and so on
# You can use these dynamic versions in config.toml for a global block break effect, just use same format
# All the events use the same format as given here
# For now there are following actions possible, all examples can be found here:
# rules: Changes the game rules, like enabling the mob spawn.
# commands: Which executes the commands given exactly.
# trades: A trader is forced to be spawned with these trades.
# messages: As demonstrated in tier-0.toml, will be sent to all online players
# trader-message: Replaces the default trader spawn message
# action-message: The message is shown above the exp bar
# The messages use a message tag system which helps you decorate them easier.
# Use a {} to define a tag and inside use following keys like {b,u,h="Example"}
# b: for bold,      u: for underline        i: for italic           r: to reset tag
# s: for strikethrough                      k: for obfuscate
# c=#RRGGBB: for rgb color                  href="LINK": for opening links
# h="TEXT": for hover text                  command="COMMAND": for running a command
# suggesst="TEXT": to suggesst a command
[on-unlock]
commands = [
    "give @a apple 8"
]

[on-unlock.rules]
doMobSpawning = true

[on-research]
trades = [
    "trade:farm-1",
    "trade:oak-saplings",
    "1xminecraft:ice; 2-4xminecraft:oak_log; 8-16xminecraft:dirt; 8-12"
]
trader-message = "{b,c=#ffffff}Wandering trader{r}: {c=#75FA8D}Don't kill me! You need my resources!"
action-message = "Neoblock is envolving... Do not worry! It will be back!"